# Generated by Django 4.2.4 on 2023-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_video_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
