# Generated by Django 4.2.4 on 2023-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_user_avatar_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.FileField(
                default="avatars/default-avatar.png", upload_to="avatars/"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
