# Generated by Django 4.2.4 on 2023-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_user_avatar_alter_video_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscribers",
            field=models.IntegerField(default=0),
        ),
    ]
