# Generated by Django 4.2.4 on 2023-09-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_video_dislikes_video_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="comments",
            field=models.IntegerField(default=0),
        ),
    ]
