# Generated by Django 4.2.4 on 2023-09-24 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 24, 19, 56, 7, 376828)
            ),
        ),
    ]
