# Generated by Django 4.2.4 on 2023-09-25 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_comment_content_alter_comment_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 16, 26, 41, 407255)
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 16, 26, 41, 407538)
            ),
        ),
    ]
