# Generated by Django 4.2.4 on 2023-09-25 20:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_video_timestamp_alter_comment_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 20, 22, 4, 828302)
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 25, 20, 22, 4, 827970)
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_likes",
                        to="app.video",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dislike",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_dislikes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_dislikes",
                        to="app.video",
                    ),
                ),
            ],
        ),
    ]
