# Generated by Django 4.2.4 on 2023-09-26 08:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_alter_comment_timestamp_alter_video_timestamp_like_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 8, 21, 23, 320570)
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 8, 21, 23, 320241)
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_creator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_subscriber",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
