# Generated by Django 4.2.4 on 2023-09-26 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_alter_comment_timestamp_alter_video_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 8, 23, 11, 672618)
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 9, 26, 8, 23, 11, 672068)
            ),
        ),
    ]
