# Generated by Django 4.2.4 on 2023-09-26 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0017_alter_comment_timestamp_alter_video_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="video",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
